#!/usr/bin/env python3
"""Render a human-readable review report from the visual asset registry."""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
REGISTRY = ROOT / "assets" / "data" / "media-assets.json"
OUTPUT = ROOT / ".github" / "visual-asset-review.md"

ORDER = [
    "REVIEW_REQUIRED",
    "MISSING_LOCAL_FILE",
    "AUTO_EXTERNAL_PREVIEW",
    "EXISTING_PUBLIC_ASSET",
]

LABELS = {
    "REVIEW_REQUIRED": "Review required",
    "MISSING_LOCAL_FILE": "Missing local file",
    "AUTO_EXTERNAL_PREVIEW": "Auto external preview",
    "EXISTING_PUBLIC_ASSET": "Existing public asset",
}


def esc(value: object) -> str:
    return str(value or "").replace("|", "\\|").replace("\n", " ")


def link(url: object, label: str) -> str:
    if not url:
        return "—"
    return f"[{label}]({url})"


def render(data: dict) -> str:
    assets = data.get("assets", [])
    groups: dict[str, list[dict]] = {}
    for item in assets:
        groups.setdefault(item.get("usage_status", "UNKNOWN"), []).append(item)

    lines = [
        "# Visual Asset Review",
        "",
        "> Auto-generated from `assets/data/media-assets.json`. Do not edit this file directly.",
        "",
        f"Generated: `{data.get('generated_at', 'unknown')}`",
        "",
        "## Summary",
        "",
        f"- Total assets: **{data.get('summary', {}).get('total', len(assets))}**",
    ]

    counts = data.get("summary", {}).get("by_usage_status", {})
    for status in ORDER:
        lines.append(f"- {LABELS[status]}: **{counts.get(status, 0)}**")

    lines += [
        "",
        "## Decision rule",
        "",
        "- `AUTO_EXTERNAL_PREVIEW`: may be used as an external platform preview.",
        "- `EXISTING_PUBLIC_ASSET`: already exists in this repository; rights are not inferred by this report.",
        "- `REVIEW_REQUIRED`: candidate only. Confirm ownership/licensing/context before reuse.",
        "- `MISSING_LOCAL_FILE`: referenced by HTML but missing from the repository.",
    ]

    seen_statuses = set(ORDER)
    statuses = ORDER + sorted(set(groups) - seen_statuses)
    for status in statuses:
        items = groups.get(status, [])
        if not items:
            continue
        lines += [
            "",
            f"## {LABELS.get(status, status.replace('_', ' ').title())}",
            "",
            "| Type | Asset | Source | Found in | Auto publish | Rights |",
            "|---|---|---|---|---:|---|",
        ]
        for item in items:
            image_url = item.get("image_url")
            source_url = item.get("source_url")
            asset_cell = link(image_url, "preview") if str(image_url or "").startswith("http") else f"`{esc(image_url)}`"
            source_cell = link(source_url, "source") if source_url else "—"
            found = "<br>".join(f"`{esc(path)}`" for path in item.get("found_in", [])) or "—"
            lines.append(
                "| {type} | {asset} | {source} | {found} | {auto} | {rights} |".format(
                    type=esc(item.get("type")),
                    asset=asset_cell,
                    source=source_cell,
                    found=found,
                    auto="YES" if item.get("auto_publish") else "NO",
                    rights=esc(item.get("rights_status")),
                )
            )

    lines += [
        "",
        "## Next review priority",
        "",
    ]
    review_items = groups.get("REVIEW_REQUIRED", [])
    if review_items:
        for item in review_items:
            lines.append(f"- Confirm reuse rights/context for `{item.get('id', 'unknown')}`.")
    else:
        lines.append("- No `REVIEW_REQUIRED` assets remain in the current registry.")

    lines.append("")
    return "\n".join(lines)


def main() -> int:
    data = json.loads(REGISTRY.read_text(encoding="utf-8"))
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(render(data), encoding="utf-8")
    print(f"Wrote {OUTPUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
